version: '3.8'

services:
  db:
    container_name: db
    image: mariadb:10-focal
    restart: always
    networks:
      - backnet
    volumes:
      - db-data:/var/lib/mysql
      - /run/secrets/db-password:/run/secrets/db-password:ro
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    ports:
      - "3306:3306"
      - "33060:33060"
    secrets:
      - db-password

  backend:
    container_name: backend
    build:
      context: backend
      target: builder
    restart: always
    networks:
      - backnet
      - frontnet
    volumes:
      - backend-data:/app/data
      - /run/secrets/db-password:/run/secrets/db-password:ro
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    ports:
      - "8000:8000"
    depends_on:
      - db
    secrets:
      - db-password

  proxy:
    container_name: proxy
    build:
      context: proxy
    restart: always
    networks:
      - frontnet
    ports:
      - "81:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  backnet:
  frontnet:

volumes:
  db-data:
  backend-data:

secrets:
  db-password:
    file: ./secrets/db-password
